// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  editor: dynamic(() => import("./Editor")),
  hero: dynamic(() => import("./Hero")),
  techlist: dynamic(() => import("./Techlist")),
};
